# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UzZDl0U3E9OmJhAQPlCX_Jx8I4yrJFn6
"""

import random

# Starting board
#
# O     X
# X
# X O O

board = [
    "O", "", "X",
    "X", "", "",
    "X", "O", "O"
]

path_cost = 0


def show():
    print()
    print(board[0], "|", board[1], "|", board[2])
    print("--+---+--")
    print(board[3], "|", board[4], "|", board[5])
    print("--+---+--")
    print(board[6], "|", board[7], "|", board[8])
    print()
    print("Path cost:", path_cost)


def win(player):
    lines = [
        (0, 1, 2),
        (3, 4, 5),
        (6, 7, 8),
        (0, 3, 6),
        (1, 4, 7),
        (2, 5, 8),
        (0, 4, 8),
        (2, 4, 6)
    ]

    return any(
        board[a] == player and
        board[b] == player and
        board[c] == player
        for a, b, c in lines
    )


def empty_boxes():
    return [i for i in range(9) if board[i] == ""]


def find_winning_move(player):
    for position in empty_boxes():

        board[position] = player

        if win(player):
            board[position] = ""
            return position

        board[position] = ""

    return None


def ai_move():

    global path_cost

    # AI tries to win
    move = find_winning_move("O")

    # AI tries to block human
    if move is None:
        move = find_winning_move("X")

    # Otherwise choose randomly
    if move is None:
        move = random.choice(empty_boxes())

    board[move] = "O"
    path_cost += 1

    print("AI made a move.")


def human_move():

    global path_cost

    while True:

        move = input("Human (X), enter position (1-9): ")

        if not move.isdigit():
            print("Enter a number from 1 to 9.")
            continue

        position = int(move) - 1

        if position < 0 or position > 8:
            print("Enter a number from 1 to 9.")

        elif board[position] != "":
            print("That position is already occupied.")

        else:
            board[position] = "X"
            path_cost += 1
            break


# -------------------------
# GAME START
# -------------------------

show()

while empty_boxes():

    # Human moves first
    human_move()
    show()

    if win("X"):
        print("Human (X) wins!")
        break

    if not empty_boxes():
        print("Draw!")
        break

    # AI moves second
    ai_move()
    show()

    if win("O"):
        print("AI (O) wins!")
        break

else:
    print("Draw!")


# -------------------------
# FINAL RESULT
# -------------------------

number_of_x = board.count("X")
number_of_o = board.count("O")

print("\n===== FINAL RESULT =====")
show()

print("Number of X:", number_of_x)
print("Number of O:", number_of_o)
print("Path cost:", path_cost)

if win("X"):
    print("Winner: Human (X)")
elif win("O"):
    print("Winner: AI (O)")
else:
    print("Result: Draw")
1


print("BHARGAV DALVI  1WA24CS084")