# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UzZDl0U3E9OmJhAQPlCX_Jx8I4yrJFn6
"""

def reflex_vacuum_agent(location, status):
    if status == 'Dirty':
        return 'Pick the Dirt'
    elif location == 'A':
        return 'Right'
    elif location == 'B':
        return 'Left'

if __name__ == "__main__":
    test_states = [
        ('A', 'Dirty'),
        ('A', 'Clean'),
        ('B', 'Dirty'),
        ('B', 'Clean')
    ]

    for loc, stat in test_states:
        action = reflex_vacuum_agent(loc, stat)
        print(f"Location: {loc} | Status: {stat} ---> Action: {action}")\


print("Bhargav Dalvi 1WA24CS084")